;;; Settings

(setq org-preview-latex-image-directory "~/.ltximg/")

(plist-put org-format-latex-options :scale 1.5)
;; (plist-put org-format-latex-options :scale 3)

(setq-default org-highlight-latex-and-related '(native))
;; Make it so you can have spaces between single dollar signs

(bz/face font-latex-math-face :bg bg :x t)
;; (bz/face org-block fixed-pitch :bg bg :h 0.9)

;;; Toggling

(defvar bz/latex-enabled t)
(defun bz/toggle-latex (&optional arg)
  (interactive)
  (setq-local bz/latex-enabled
              (if (numberp arg)
                  (if (eq arg 0) bz/latex-enabled
                    (if (< arg 0) nil t))
                (not bz/latex-enabled)))
  (if bz/latex-enabled
      (org-latex-preview '(16))
    (org-latex-preview '(64))))

(bz/package org-fragtog)

(bz/keys org-mode-map
  "C-c C-l" nil
  "C-c C-l C-l" ((org-latex-preview '(16)) (org-fragtog-mode 0))
  "C-c C-l C-o" ((org-latex-preview '(64)) (org-fragtog-mode 0))
  "C-c C-l C-f" ((org-latex-preview '(16)) (org-fragtog-mode 1))
  "C-c C-l C-t" bz/toggle-latex

  "C-l" bz/toggle-latex

  "M-\\" ((insert "$$") (backward-char 1) (bz/insert))
  ;; "M-|"  ((insert "\\[  \\]") (backward-char 3) (bz/insert))
  )



;;; Snippets

(defun bz/snippet-math-pattern ()
  (interactive)
  (let* ((term (if mark-active (buffer-substring (point) (mark)) (read-string "Term: ")))
         (sep (string (read-char "Separator: ")))
         (min (read-string "Min: "))
         (min+1 (if (not (string-match-p "[0-9]+" min)) (format "%s+1" min)
                  (number-to-string (1+ (string-to-number min)))))
         (max (read-string "Max: "))
         (term0 (replace-regexp-in-string "!" min term))
         (term1 (replace-regexp-in-string "!" min+1 term))
         (termn (replace-regexp-in-string "!" max term)))

    (when mark-active (delete-region (point) (mark)))
    (insert (format "%s %s %s %s ... %s %s" term0 sep term1 sep sep termn))))
(bz/keys bz/selection-map
  "!" bz/snippet-math-pattern)

(setf (alist-get 'org-mode bz/snippet-mode-alist)
      '(
        ("b s" "\\{ <<>>_j \\}_{j=1}^{\\infty}")
        ("!" bz/snippet-math-pattern)

        ("h t" "#+title: ")
        ("h i" "#+latex_header: \\setlength{\\parindent}{0pt}")
        ("h m" "#+latex_header: \\newcommand{\\Mod}[1]{\\ (\\mathrm{mod}\\ #1)}")
        ("h g" "#+latex_header: \\usepackage[margin=1in]{geometry}")
        ("h s" "#+latex_header: \\AddToHook{cmd/section/before}{\\newpage}")
        ("h p" "#+latex: \\newpage")
        ("h C-i" "#+latex_header: \\newcommand{\\tab}[0]{|\\quad}")

        ("(" "\\left( <<>> \\right)")
        ("[" "\\left[ <<>> \\right]")
        (")" "\\left[ <<>> \\right)")
        ("]" "\\left( <<>> \\right]")
        ("{" "\\left\\{ <<>> \\right\\}")
        ("\\" "\\left< <<>> \\right>")
        ("|" "\\left| <<>> \\right|")
        ("1" "^{-1}")
        ("2" "^2")
        ("k" "^")
        ("j" "_")
        ("K" "^{<<>>}")
        ("J" "_{<<>>}")
        ("I" " \\in ")
        ("t" "\\text{<<>>}")
        ("T" "\\text{ <<>> }")
        ("M" "\\Mod{<<>>}")
        ("S" "\\star")
        ("x" "\\cdot")
        ("X" "\\times")
        ("D" "\\displaystyle")
        ("$" "\\textdollar")
        ("Q" "\\square")

        ("=" "\\equiv")
        ("~" "\\widetilde{<<>>}")
        ("` `" "\\sim")
        ("` ~" "\\approx")
        ("` -" "\\simeq")
        ("` =" "\\cong")
        ("` p" "\\propto")

        ("F" "\\frac{<<>>}{}" )
        ("f 1" "\\frac{1}{<<>>}")
        ("f 2" "\\frac{1}{2}")

        ("," "\\leftarrow")
        ("." "\\rightarrow")
        ("/" "\\leftrightarrow")
        ("<" "\\Leftarrow")
        (">" "\\Rightarrow")
        ("?" "\\Leftrightarrow")
        ("a k" "\\uparrow")
        ("a K" "\\Uparrow")
        ("a j" "\\downarrow")
        ("a J" "\\Downarrow")
        ("a v" "\\updownarrow")
        ("a V" "\\Updownarrow")

        ("s c" "\\circ")
        ("s s" "\\left\\{ <<>> \\right\\}")
        ("s m" "\\setminus")
        ("s ," "\\subseteq")
        ("s ." "\\supseteq")
        ("s u" "\\cup")
        ("s U" "\\bigcup_{<<>>}^{}")
        ("s i" "\\cap")
        ("s I" "\\bigcap_{<<>>}^{}")
        ("s e" "\\emptyset")
        ("s t" "\\triangle")
        ("s b" "\\bar{<<>>}")
        ("s o" "\\overline{<<>>}")
        ("s O" "\\underline{<<>>}")
        ("s n" "\\trianglelefteq") ; Normal
        ("s +" "\\oplus") ; Direct sum
        ("s X" "\\otimes") ; Direct sum

        ("g a" "\\alpha") ("g A" "\\Alpha")
        ("g b" "\\beta") ("g B" "\\Beta")
        ("g g" "\\gamma") ("g G" "\\Gamma")
        ("g d" "\\delta") ("g D" "\\Delta")
        ("g e" "\\varepsilon") ("g E" "\\Epsilon")
        ("g l" "\\lambda") ("g L" "\\Lambda")
        ("g m" "\\mu") ("g M" "\\Mu")
        ("g n" "\\nu") ("g N" "\\Nu")
        ("g o" "\\omega") ("g O" "\\Omega")
        ("g r" "\\rho") ("g R" "\\Rho")
        ("g s" "\\sigma") ("g S" "\\Sigma")
        ("g t" "\\theta") ("g T" "\\Theta")
        ("g u" "\\tau") ("g U" "\\Tau")
        ("g z" "\\zeta") ("g Z" "\\Zeta")

        ("m r" "\\sqrt{<<>>}")
        ("m R" "\\sqrt[<<>>]{}")
        ("m f" "\\lfloor <<>> \\rfloor")
        ("m c" "\\lceil <<>> \\rceil")
        ("m s" "\\sum_{<<>>}^{}")
        ("m S" "\\sum_{<<>>}^{\\infty}")
        ("m p" "\\prod_{<<>>}^{}")
        ("m P" "\\prod_{<<>>}^{\\infty}")
        ("m i" "\\int_{<<>>}^{}")
        ("m I" "\\int_{<<>>}^{\\infty}")
        ("m l" "\\lim_{<<>> \\rightarrow }")
        ("m L" "\\lim_{<<>> \\rightarrow \\infty}")

        ("p p" "\\text{Pr}\\left[ <<>> \\right]")
        ("p e" "\\text{E}\\left[ <<>> \\right]")
        ("p v" "\\text{Var}\\left[ <<>> \\right]")
        ("p c" "{<<>> \\choose }")
        ("p C" "\\text{Cov}\\left[ <<>> \\right]")
        ("p t" "\\hat{\\theta}")

        ("l ." "\\mapsto") ; Arrow with bar
        ("l e" "\\exists")
        ("l f" "\\forall")
        ("l n" "\\neg")
        ("l a" "\\land")
        ("l o" "\\lor")
        ("l c" "\\circ") ; Compose
        ("l i" "\\text{im}\\,")
        ("l k" "\\ker")

        ("r b" "#+begin_box\n<<>>\n#+end_box")
        ("r d" "#+begin_definition <<>>\n\n#+end_definition")
        ("r t" "#+begin_theorem\n<<>>\n#+end_theorem")
        ("r p" "#+begin_proof\n<<>>\n#+end_proof")
        ("r a" "\\begin{align*}\n<<>>\n\\end{align*}")
        ("r c" "\\begin{cases} <<>> \\end{cases}")
        ("r m" "\\begin{matrix} <<>> \\end{matrix}")

        ("b x" "\\mathbf{x}")
        ("b z" "\\mathbb{Z}")
        ("b -" "\\mathbb{Z}_-")
        ("b =" "\\mathbb{Z}_+")
        ("b 0" "\\mathbb{Z}_{\\ge 0}")

        ("b r" "\\mathbb{R}")
        ("b R" "\\mathbb{R}^n")
        ("b _" "\\mathbb{R}_-")
        ("b +" "\\mathbb{R}_+")
        ("b )" "\\mathbb{R}_{\\ge 0}")

        ("b n" "\\mathbb{N}")
        ("b q" "\\mathbb{Q}")
        ("b c" "\\mathbb{C}")
        ("b f" "\\mathbb{F}")
        ("b i" "\\infty")
        ("b l" "\\ell")
        ("b p" "\\partial")

        ("f a" "\\mathcal{A}")
        ("f b" "\\mathcal{B}")
        ("f c" "\\mathcal{C}")
        ("f d" "\\mathcal{D}")
        ("f e" "\\mathcal{E}")
        ("f f" "\\mathcal{F}")
        ("f g" "\\mathcal{G}")
        ("f h" "\\mathcal{H}")
        ("f i" "\\mathcal{I}")
        ("f j" "\\mathcal{J}")
        ("f k" "\\mathcal{K}")
        ("f l" "\\mathcal{L}")
        ("f m" "\\mathcal{M}")
        ("f n" "\\mathcal{N}")
        ("f o" "\\mathcal{O}")
        ("f p" "\\mathcal{P}")
        ("f q" "\\mathcal{Q}")
        ("f r" "\\mathcal{R}")
        ("f s" "\\mathcal{S}")
        ("f t" "\\mathcal{T}")
        ("f u" "\\mathcal{U}")
        ("f v" "\\mathcal{V}")
        ("f w" "\\mathcal{W}")
        ("f x" "\\mathcal{X}")
        ("f y" "\\mathcal{Y}")
        ("f z" "\\mathcal{Z}")))

;;; Prettify

(defvar bz/org-latex-font-lock-keywords nil)
(defmacro bz/org-make-font-lock-keywords (&rest replacements)
  `(progn
     (font-lock-remove-keywords 'org-mode bz/org-latex-font-lock-keywords)
     (setq bz/org-latex-font-lock-keywords
           (--map `(,(concat (regexp-quote (car it))
                             (if (caddr it) "\\>" ""))
                    (0 (ignore (compose-region (match-beginning 0) (match-end 0) ,(cadr it)))))
                  ,(list '\` replacements)))
     (font-lock-add-keywords 'org-mode bz/org-latex-font-lock-keywords)))


(bz/org-make-font-lock-keywords
 ("\\[" "⟦")
 ("\\]" "⟧")
 ("\\(" "⟨")
 ("\\)" "⟩")
 ("\\left[" "⟦")
 ("\\right]" "⟧")
 ("\\left(" "⟬")
 ("\\right)" "⟭")
 ("\\left\\{" "⦃")
 ("\\right\\}" "⦄")

 ("\\sqrt" "√")
 ("\\cdot" "∙")
 ("\\times" "×")
 ("\\otimes" "")
 ("\\oplus" "⨁")
 ("\\otimes" "⨂")
 ("\\equiv" "≡")

 ("\\Rightarrow" "⇒")
 ("\\Leftarrow" "⇐")
 ("\\Uparrow" "⇑")
 ("\\Downarrow" "⇓")
 ("\\rightarrow" "→")
 ("\\leftarrow" "←")
 ("\\uparrow" "↑")
 ("\\downarrow" "↓")
 ("\\leftrightarrow" "↔")
 ("\\Leftrightarrow" "⇔")
 ("\\updownarrow" "↕")
 ("\\Updownarrow" "⇕")
 ("\\mapsto" "⟼")

 ("\\lfloor" "⌊")
 ("\\rfloor" "⌋")
 ("\\rceil" "⌈")
 ("\\lceil" "⌉")
 ("\\left|" "⎢")
 ("\\right|" "⎥")

 ("\\sum" "Σ")
 ("\\prod" "Π")
 ("\\int" "∫")
 ("\\oint" "∮")

 ("\\neg" "¬")
 ("\\land" "∧")
 ("\\lor" "∨")
 ("\\circ" "∘") ; Compose
 ("\\in" "∈" t)
 ("\\notin" "∉")
 ("\\subseteq" "⊆")
 ("\\not\\subseteq" "⊄")
 ("\\supseteq" "⊇")
 ("\\not\\supseteq" "⊈")
 ("\\cap" "∩")
 ("\\cup" "∪")
 ("\\bigcap" "⋂")
 ("\\bigcup" "⋃")
 ("\\emptyset" "∅")
 ("\\setminus" "∖")
 ("\\triangle" "∆" t)
 ("\\trianglelefteq" "⊴" t)
 ("\\exists" "∃")
 ("\\not\\exists" "∄")
 ("\\forall" "∀")
 ("\\infty" "∞")
 ("\\ne" "≠" t)
 ("\\ge" "≥" t)
 ("\\le" "≤" t)
 ("\\square" "□")

 ("\\mathbb{C}" "ℂ")
 ("\\mathbb{H}" "ℍ")
 ("\\mathbb{N}" "ℕ")
 ("\\mathbb{P}" "ℙ")
 ("\\mathbb{Q}" "ℚ")
 ("\\mathbb{R}" "ℝ")
 ("\\mathbb{Z}" "ℤ")
 ("\\mathbb{F}" "𝔽")
 ("\\partial" "∂")

 ("\\ell" "ℓ")
 ("\\overline" "﹉")

 ("\\cong" "≅")
 ("\\approx" "≈")
 ("\\sim" "~")
 ("\\simeq" "≃")
 ("\\propto" "∝")

 ;; ("\\frac" "𝕗")
 ;; ("\\frac{1}{2}" "½")
 ;; ("\\frac{1}{3}" "⅓")
 ;; ("\\frac{1}{4}" "¼")

 ("\\begin{matrix}" "▦")
 ("\\end{matrix}" "▥")

 ("\\Alpha"   "Α") ("\\alpha"   "α")
 ("\\Beta"    "Β") ("\\beta"    "β")
 ("\\Gamma"   "Γ") ("\\gamma"   "γ")
 ("\\Delta"   "Δ") ("\\delta"   "δ")
 ("\\Epsilon" "Ε") ("\\epsilon" "ϵ") ("\\varepsilon" "ε")
 ("\\Zeta"    "Ζ") ("\\zeta"    "ζ")
 ("\\Eta"     "Η") ("\\eta"     "η")
 ("\\Theta"   "Θ") ("\\theta"   "θ")
 ("\\Iota"    "Ι") ("\\iota"    "ι")
 ("\\Kappa"   "Κ") ("\\kappa"   "κ")
 ("\\Lambda"  "Λ") ("\\lambda"  "λ")
 ("\\Mu"      "Μ") ("\\mu"      "μ")
 ("\\Nu"      "Ν") ("\\nu"      "ν")
 ("\\Xi"      "Ξ") ("\\xi"      "ξ")
 ("\\Omikron" "Ο") ("\\omikron" "ο")
 ("\\Pi"      "Π") ("\\pi"      "π")
 ("\\Rho"     "Ρ") ("\\rho"     "ρ")
 ("\\Sigma"   "Σ") ("\\sigma"   "σ")
 ("\\Tau"     "Τ") ("\\tau"     "τ")
 ("\\Upsilon" "Υ") ("\\upsilon" "υ")
 ("\\Phi"     "Φ") ("\\phi"     "ϕ") ("\\varphi" "φ")
 ("\\Chi"     "Χ") ("\\chi"     "χ")
 ("\\Psi"     "Ψ") ("\\psi"     "ψ")
 ("\\Omega"   "Ω") ("\\omega"   "ω")

 ("\\mathcal{A}" "𝓐") ("\\mathcal{B}" "𝓑")
 ("\\mathcal{C}" "𝓒") ("\\mathcal{D}" "𝓓")
 ("\\mathcal{E}" "𝓔") ("\\mathcal{F}" "𝓕")
 ("\\mathcal{G}" "𝓖") ("\\mathcal{H}" "𝓗")
 ("\\mathcal{I}" "𝓘") ("\\mathcal{J}" "𝓙")
 ("\\mathcal{K}" "𝓚") ("\\mathcal{L}" "𝓛")
 ("\\mathcal{M}" "𝓜") ("\\mathcal{N}" "𝓝")
 ("\\mathcal{O}" "𝓞") ("\\mathcal{P}" "𝓟")
 ("\\mathcal{Q}" "𝓠") ("\\mathcal{R}" "𝓡")
 ("\\mathcal{S}" "𝓢") ("\\mathcal{T}" "𝓣")
 ("\\mathcal{U}" "𝓤") ("\\mathcal{V}" "𝓥")
 ("\\mathcal{W}" "𝓦") ("\\mathcal{X}" "𝓧")
 ("\\mathcal{Y}" "𝓨") ("\\mathcal{Z}" "𝓩"))
